# Generated by Django 2.0.3 on 2018-04-18 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorstockItem',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'floorstock_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionStatistic',
            fields=[
                ('batch_number', models.ForeignKey(db_column='batch_number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='operations.Batch')),
                ('time_stamp', models.DateTimeField()),
                ('production_quantity', models.IntegerField(blank=True, null=True)),
                ('staff_quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'production_statistic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FloorstockStatistic',
            fields=[
                ('floorstock_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='prodStat.FloorstockItem')),
                ('time_stamp', models.DateTimeField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'floorstock_statistic',
                'managed': False,
            },
        ),
    ]
