# Generated by Django 2.0.3 on 2018-05-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionStatistic',
            fields=[
                ('time_stamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('production_quantity', models.IntegerField(blank=True, null=True)),
                ('staff_quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'production_statistic',
                'ordering': ['-time_stamp'],
                'managed': False,
            },
        ),
    ]
