# Generated by Django 2.0.3 on 2018-05-11 08:24


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloorstockItem',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'floorstock_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FloorstockStatistic',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'floorstock_statistic',
                'ordering': ['-time_stamp'],
                'managed': False,
            },
        ),
    ]
