# Generated by Django 2.0.3 on 2018-04-23 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloorstockItem',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'floorstock_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FloorstockStatistic',
            fields=[
                ('floorstock_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='floorstock.FloorstockItem')),
                ('time_stamp', models.DateTimeField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'floorstock_statistic',
                'managed': False,
            },
        ),
    ]
