# Generated by Django 2.0.3 on 2018-03-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('scrap', models.IntegerField(blank=True, null=True)),
                ('yield_1', models.IntegerField(blank=True, null=True)),
                ('hmi1_good', models.IntegerField(blank=True, db_column='HMI1_good', null=True)),
                ('hmi1_bad', models.IntegerField(blank=True, db_column='HMI1_bad', null=True)),
                ('hmi2_good', models.IntegerField(blank=True, db_column='HMI2_good', null=True)),
                ('hmi2_bad', models.IntegerField(blank=True, db_column='HMI2_bad', null=True)),
                ('rework_date', models.DateTimeField(blank=True, null=True)),
                ('applied_labels', models.IntegerField(blank=True, null=True)),
                ('label_print_time', models.DateTimeField(blank=True, null=True)),
                ('rework_time', models.TimeField(blank=True, null=True)),
                ('yield_2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'batch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BatchComment',
            fields=[
                ('comment_id', models.IntegerField(db_column='comment_ID', primary_key=True, serialize=False)),
                ('post_date', models.DateTimeField(blank=True, null=True)),
                ('text_comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'batch_comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('article_number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_storage', models.IntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('order_number', models.CharField(max_length=7, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_order',
                'managed': False,
            },
        ),
    ]
